/**
 * Known-answer test for deriveLibp2pIdentity.
 *
 * The expected values were generated by a standalone Rust program that uses
 * the same algorithm as eigenwallet's swap/src/seed.rs::derive_libp2p_identity
 * (SHA-256(seed || "NETWORK") → SHA-256(that || "LIBP2P_IDENTITY") →
 * Ed25519::from_bytes → libp2p peer-id).
 *
 * Any drift on either side — ours (TS) or eigenwallet's Rust — produces a
 * different peer-id and this test fails. That's the whole point of the KAT:
 * cross-binary recovery only works if both sides derive the same peer-id
 * from the same master seed.
 *
 * Generator: /tmp/rust-kat/src/main.rs + Cargo.toml (libp2p 0.53, sha2 0.10).
 */
import { describe, it, expect } from 'vitest';
import { deriveLibp2pIdentity } from '../../../src/lib/crypto/libp2p-identity.js';

interface KatVector {
  readonly seed: string;
  readonly libp2pSeedHex: string;
  readonly libp2pPeerId: string;
  readonly pubkeyProto: string;
}

const VECTORS: readonly KatVector[] = [
  {
    seed: '0000000000000000000000000000000000000000000000000000000000000000',
    libp2pSeedHex: '8a23e6a794c1977f67ebadaa54f05d8c84f86c12ae8e3155c8e9621559477587',
    libp2pPeerId: '12D3KooWHuLnU4ge4D8B5giEWLeKtzUDwprzDwwQvvPBYsuDQVaL',
    pubkeyProto: '080112207823d59f779a9e73f853e1b0b7ef0715cb4aeab500811f1773be12ba79eec255',
  },
  {
    seed: '1111111111111111111111111111111111111111111111111111111111111111',
    libp2pSeedHex: '0531daa10c2abca1ce2e5bf0fcf17cfc489d7c27bd97ab83e0292ce19edf2526',
    libp2pPeerId: '12D3KooWSgoKbmtWZ28bw7ENXSHf1XLZtudifRd3ziYfvqgFxPZP',
    pubkeyProto: '08011220faa678b4ebf52d1ea6d4ed28e1a807328b4ce9f2cb7863ace0870fa57a2079c6',
  },
  {
    seed: 'deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef',
    libp2pSeedHex: '67cf83987e98216a2c353e7e2aa017a11c970e0a5cd95ac077aa3cd54fa0317d',
    libp2pPeerId: '12D3KooWQdq47V84oYs5YxQokSrtD7TiXqdTA9AJcdcf5WF4ryMc',
    pubkeyProto: '08011220dc2c5090940ee271050b80ac30d871453c93cbb123537349204072bf9a000763',
  },
  {
    seed: 'abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789',
    libp2pSeedHex: '6c6e946c6629b9f9b6750bb045466dfe16371c7fa3c7546081b19cfe7aa00bc7',
    libp2pPeerId: '12D3KooWFJDQN8Y93GLE6YYfkGkFFn34orrdi5TdzkSuGAV76jQ2',
    pubkeyProto: '08011220516cc95736631f834668f26dbe61b0c4800b1fce198d8c2a0c0d60fe13f76387',
  },
];

describe('deriveLibp2pIdentity', () => {
  for (const v of VECTORS) {
    it(`matches eigenwallet Rust for seed ${v.seed.slice(0, 8)}…`, async () => {
      const r = await deriveLibp2pIdentity(v.seed);
      expect(r.libp2pSeedHex).toBe(v.libp2pSeedHex);
      expect(r.libp2pPeerId).toBe(v.libp2pPeerId);
      expect(r.libp2pPublicKeyProtoHex).toBe(v.pubkeyProto);
    });
  }

  it('rejects non-32-byte seeds', async () => {
    await expect(deriveLibp2pIdentity('00'.repeat(31))).rejects.toThrow();
    await expect(deriveLibp2pIdentity('00'.repeat(33))).rejects.toThrow();
  });
});
