// Canonical codes for VerificationError and ProtocolError. Consumers switch
// on `code` for stable UI. Human-readable reference: docs/ERROR-CODES.md.
export const ERROR_CODES = {
  E_REDEEM_DIGEST_MISMATCH: 'Local redeem digest differs from sidecar claim',
  E_LOCK_ADDR_MISMATCH: 'Derived P2WSH address differs from sidecar claim',
  E_LOCK_SCRIPT: 'Failed to derive P2WSH from (A, B)',
  E_S_A_MISMATCH: 'Sidecar s_a does not satisfy s_a * G == S_a_monero',
  E_S_A_MONERO_MISSING: 'Protocol params missing S_a_monero',
  E_COOP_SA_ADAPTOR_MISMATCH: 'Cooperative s_a fails adaptor-target check',
  E_COOP_SA_PUBKEY_MISMATCH: 'Cooperative s_a does not hash to S_a_monero',
  E_AMNESTY_EXCEEDS_CAP: 'Amnesty exceeds configured ratio cap',
  E_AMNESTY_NEGATIVE: 'Amnesty amount is negative',
  E_FEE_BELOW_RELAY: 'Fee below relay floor',
  E_FEE_ABOVE_CAP: 'Fee above sanity ceiling',
  E_OUTPUT_DUST: 'Output below dust floor',
  E_XMR_LOCK_FAILED: 'XMR lock verification failed',
  E_XMR_TIMELOCKED_OUTPUT: 'Monero output has non-zero unlock_time',
  E_QUORUM_IMPOSSIBLE: 'Quorum target exceeds provider count',
  E_QUORUM_DISAGREE: 'Providers did not reach quorum',
  E_MONERO_QUORUM: 'Not enough Monero nodes responded',
  E_DEST_ADDR_INVALID: 'Destination address invalid for network',
  E_PROVIDER_UNKNOWN: 'Unknown swap provider',
  E_PROTOCOL_PARAMS_MISSING: 'Protocol params expected but absent',
  E_NO_SIGNED_PSBT: 'Need locally-signed PSBT to recompute digest',
  E_DRIVE_TIMEOUT: 'Swap driver exceeded wall-clock budget',
  E_TERMINAL: 'Swap reached terminal state',
  E_WASM_INTEGRITY: 'WASM SHA-256 integrity check failed',
  E_KEYSTORE_V1_INCOMPLETE: 'V1 keystore migration missing required field',
  E_ENCSIG_SUBMIT_FAILED: 'Encsig submission exceeded retry budget',
  E_MEMO_MALFORMED: 'THORChain memo does not parse',
  E_MEMO_DEST_MISMATCH: 'THORChain memo destination differs from expected',
  E_THORCHAIN_QUORUM: 'Too few THORChain vault sources responded',
  E_THORCHAIN_VAULT_DISAGREE: 'THORNode and Midgard disagree on vault',
  E_VAULT_UNKNOWN: 'Sidecar-claimed vault does not appear in authoritative list',
  E_VAULT_HALTED: 'THORChain vault or chain trading is halted',
  E_THORNODE_QUOTE_UNAVAILABLE: 'Could not fetch THORNode quote',
  E_UNEXPECTED_TIMELOCK: 'timelock_blocks set for non-atomicswap provider',
  E_CHAINFLIP_SHAPE: 'Chainflip response failed schema validation',
  E_CHAINFLIP_HTTP: 'Chainflip broker returned error status',
  E_CHAINFLIP_TIMEOUT: 'Chainflip channel not found within timeout',
  E_CHAINFLIP_CHANNEL_DISAGREE: 'Broker and state-chain disagree on channel',
  E_CHAINFLIP_CHANNEL_MISBINDING: 'Channel does not bind user destination / refund',
  E_CHAINFLIP_CHANNEL_EXPIRING: 'Channel expires before funding can confirm',
  E_CHAINFLIP_AMOUNT_BELOW_MIN: 'Deposit amount below channel minimum',
  E_CHAINFLIP_AMOUNT_ABOVE_MAX: 'Deposit amount above channel maximum',
  E_NEAR_INTENT_NOT_REGISTERED: 'Intent not found on 1Click',
  E_NEAR_INTENT_EXPIRED: 'Intent deadline passed',
  E_NEAR_INTENT_EXPIRING: 'Intent deadline too close to funding confirmation',
  E_NEAR_INTENT_FAILED: '1Click reports intent failed',
  E_NEAR_INTENT_MISBINDING: 'Intent does not bind user destination / refund',
  E_NEAR_INTENT_CHAIN_DEST: 'On-chain intent destination differs from 1Click claim',
  E_NEAR_INTENT_CHAIN_AMOUNT: 'On-chain intent amount differs from 1Click claim',
  E_RATE_DRIFT: 'Engine expected output outside slippage band',
  E_QUOTE_DRIFT: 'Server quote drifted from accepted quote beyond slippage',
  E_QUOTE_TAMPERED: 'Server quote hash does not match accepted quote',
  E_QUOTE_STALE: 'Accepted quote exceeds max age, re-quote required',
  E_ORACLE_QUORUM: 'Too few rate oracles responded',
  E_ORACLE_SPREAD: 'Rate oracles disagree beyond threshold',
  E_RATE_DEVIATION: 'Engine rate deviates from oracle median beyond threshold',
  E_PROVIDER_UNSUPPORTED_REFUND: 'Provider does not support refund-address binding',
  E_DEPOSIT_TOO_MANY_UTXOS: 'Deposit address received too many UTXOs',
  E_SWEEP_DUST: 'Sweep output below dust floor',
  E_SLIPPAGE_OUT_OF_RANGE: 'slippageBps out of permitted range',
  E_INVALID_DEST_ADDRESS: 'destAddress is not valid for the destination token',
  E_POLL_OUT_OF_RANGE: 'pollMs out of permitted range',
  E_RETRIES_OUT_OF_RANGE: 'maxRetries out of permitted range',
  E_PROVIDER_SUBSTITUTED: 'Server returned a different provider than requested',
  E_VERIFICATION_ABSENT: 'Server has not produced a verification after retry budget',
  E_TX_CANCEL_UNVERIFIED: 'TxCancel not confirmed on-chain',
  E_TX_CANCEL_MALFORMED: 'TxCancel hex did not parse',
  E_ENCSIG_REFUND_INVALID: 'Alice encsig_refund did not verify under recomputed digest',
  E_ENCSIG_REFUND_MISSING: 'Server did not provide tx_full_refund_encsig at setup',
  E_REFUND_DUST: 'Refund output below dust floor',
  E_AMNESTY_DUST: 'Amnesty output below dust floor',
  E_AMNESTY_DERIVE: 'Failed to derive amnesty P2WSH',
  E_REFUND_SIG_A: 'Alice sig on TxRefund failed local verification',
  E_REFUND_SIG_B: 'Bob sig on TxRefund failed local verification',
  E_REFUND_BROADCAST: 'Refund broadcast failed',
  E_SIG_HIGH_S: 'Signature is not in low-S form',
  E_REFUND_PARAMS_MISSING: 'Refund protocol params absent from server response',
  E_SNAPSHOT_WRITE_FAILED: 'Failed to persist recovery snapshot before broadcast',
  E_LIBP2P_SEED_REQUIRED:
    'Keystore has no libp2p master seed \u2014 legacy V2 keystores cannot start new swaps. Create a new keystore.',
  E_TIMELOCK_OUT_OF_RANGE: 'BIP68 sequence supplied by sidecar is outside the accepted range',
  E_DLEQ_PROOF_REQUIRED: 'Alice DLEQ proof is required before funding; refusing to proceed without it',
  E_DLEQ_PROOF_INVALID: 'Alice DLEQ proof failed cross-curve verification',
  E_PRESIGS_WEDGED:
    'Sidecar repeatedly rejected /presigs with "no pending PSBT" while the encsig never appeared on /getSwapDetail. The sidecar broker is out of sync with crypto-server\'s view; the swap cannot progress without operator intervention.',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
