#!/usr/bin/env node
// Generate src/wasm-pins.ts from the unified WASM binary.
// Idempotent: running twice produces no diff.

import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const SWAP = join(root, 'wasm/miradex-rust/miradex_rust_bg.wasm');

function sha(path) {
  const bytes = readFileSync(path);
  return createHash('sha256').update(bytes).digest('hex');
}

const hash = sha(SWAP);

const body = `/* AUTO-GENERATED by scripts/pin-wasm.mjs — do not edit by hand. */
export const SWAP_WASM_SHA256 = ${JSON.stringify(hash)};
/* Legacy aliases (removed in 0.4.0): */
export const KEYGEN_WASM_SHA256 = SWAP_WASM_SHA256;
export const MONERO_SWEEP_WASM_SHA256 = SWAP_WASM_SHA256;
`;

writeFileSync(join(root, 'src/wasm-pins.ts'), body);
console.log('Wrote src/wasm-pins.ts');
