/* AUTO-GENERATED by scripts/pin-wasm.mjs — do not edit by hand. */
export const SWAP_WASM_SHA256 = "df3578008826998fcf76d02c2925a10a59b6b657d3f83d79edfcfc4ce9a980f3";
/* Legacy aliases (removed in 0.4.0): */
export const KEYGEN_WASM_SHA256 = SWAP_WASM_SHA256;
export const MONERO_SWEEP_WASM_SHA256 = SWAP_WASM_SHA256;
