/* AUTO-GENERATED by scripts/pin-wasm.mjs — do not edit by hand. */
export const SWAP_WASM_SHA256 = "2450ea115d826df77f6c021e9b120004fcb6fe7f7e1aa922cd1caab6e76817a3";
/* Legacy aliases (removed in 0.4.0): */
export const KEYGEN_WASM_SHA256 = SWAP_WASM_SHA256;
export const MONERO_SWEEP_WASM_SHA256 = SWAP_WASM_SHA256;
