/* AUTO-GENERATED by scripts/pin-wasm.mjs — do not edit by hand. */
export const SWAP_WASM_SHA256 = "beac671540e948a7b8b1d049f068dc7a3e754bf7745cbb5074cdbc88e25683d9";
/* Legacy aliases (removed in 0.4.0): */
export const KEYGEN_WASM_SHA256 = SWAP_WASM_SHA256;
export const MONERO_SWEEP_WASM_SHA256 = SWAP_WASM_SHA256;
